### ISSUE TITLE
* /window: invalid parameters (line 335, i2.mrc)

### ISSUE THREAD

**Issue by KoraggKnightWolf** [peace-and-protection/i2#1]
When attempting to open the configuration menu, the error in the title occurs: * /window: invalid parameters (line 335, i2.mrc) When looking at line 335 in e.g. Notepad++ the alias cfg is the source of the problem. mIRC version is 7.61. 
It appears that others do not have this issue but just incase, I wish to document it here.

Regards,

Koragg

**Comment by ghost** [comment]
As per conversation on IRC, here's the I2.MSI file to see if that still has an issue...
We can try this out if all else fails...

edit: removed i2.zip

**Comment by ghost** [comment]
The above msi might not work with portable mirc...Untested. However it was proven that i2.mrc runs well and without the above error in its own environment.

Steps for creating environment manually:
1. go to windows explorer and navigate to %appdata% 
2. create a new folder in it called 'i2mirc' 
3. copy the i2.mrc and i2.txt files in there 
4. create a new shortcut on the desktop and point it to "c:\program files (x86)\mirc\mirc.exe" -r%appdata%\i2mirc
5. Run the shortcut and load i2 just the once by typing `/load -rs i2.mrc`

**Comment by KoraggKnightWolf** [comment]
Using the provided i2.msi creates a working mIRC shortcut with no issues. Therefor the problem I'm experiencing is not due to this addon and thus I will close this issue again.

**Comment by ghost** [comment]
According to @KoraggKnightWolf , the error occurs when copy pasting i2.mrc when the file is viewed in raw mode on github. Hence, if you are planning on installing i2, please use the green download zip button in the code section on the repository!
